### ISSUE TITLE
source maps for server code

### ISSUE THREAD

**Issue by GiladShoham** [sysgears/apollo-fullstack-starter-kit#18] opened 2017-01-08 14:31 UTC
I saw few configurations related to source maps like:
```js
new webpack.BannerPlugin('require("source-map-support").install();',
      { raw: true, entryOnly: false }),

devtool: __DEV__ ? '#cheap-module-source-map' : '#source-map',

devtool: __DEV__ ? '#eval' : '#source-map',
```

But yet when I have an error in my console I see it referring to the bundled file:
```
{ Error: some error
    at Function.addShowingRequest (my-app-path/build/server/0.d2049b2bca4ab66ea103.hot-update.js:96:14)
    at addShowingRequest (my-app-path/build/server/index.js:3948:47)
```

Is there anything else need to be configured to make it work?
Thanks!

**Comment by vlasenko** [comment] 2017-01-10 17:23
After some investigation, I see that this problem is joint problem of `source-map-support` and `webpack` hot module replacement behavior. The easiest way to solve it is to fork `source-map-support` npm package and modify it to understand `webpack` behavior during hot module replacement. This is quite a big effort.

**Comment by GiladShoham** [comment] 2017-01-11 09:12
Thanks for the update!

**Comment by vlasenko** [comment] 2017-01-11 09:20
@GiladShoham I've spent much time investigating this problem. But I feel more time need to be invested to understand the root cause of the problem. I've checked all webpack configuration options, then all source-map-support options and stopped on investigation of generated source map format for hot replacement code. Hopefully, I will revisit this issue later, when I have more time.

**Comment by vlasenko** [comment] 2017-01-11 15:56
@GiladShoham I think it's more a problem of `source-map-support` node.js module then `webpack`. Seems `source-map-support` doesn't expect that hot module replacement can happen at runtime, it needs to be modified to be aware of that.

**Comment by GiladShoham** [comment] 2017-01-11 18:41
Hi,
I really appreciate your time!

do you want me to open an issue?
do you think this repo is the right place?
https://github.com/evanw/node-source-map-support

**Comment by vlasenko** [comment] 2017-01-11 20:06
Hi,

At this point I don't fully understand the reason for the issue. I think that the source maps for hot reloaded modules do not make into global source map registry used by `source-map-support` module, hence for hot reloaded modules source maps are not used at all. I plan to look and confirm this tomorrow.
Victor

**Comment by vlasenko** [comment] 2017-01-12 09:44
@GiladShoham 

So the showstopper for me is `webpack`. Even when you completely switch off `devtool`, after hot module replacement happens, the lines inside hot-update.js files in stack traces are unpredictably wrong. This is very very strange and needs something to have with how `hot-update.js` files get executed from file system. This problem is not related to source maps at all. So the main bug is lines in stack frames from `hot-update.js` files are wrong and this is `webpack` related problem.

If the lines from `hot-update.js` files will be correct, there are also issues with `source-map-support` and `babel`, but I have already implemented the working solution around this. The only thing I need is lines from stack frames of `hot-update.js` to be correct.

**Comment by GiladShoham** [comment] 2017-01-12 14:15
@vlasenko 
If you want me to somehow help you with this, just let me know.

**Comment by vlasenko** [comment] 2017-01-12 15:48
@GiladShoham Thanks for reporting this one. It was very hard to debug, but should be fixed now, please check. The relevant commit:
https://github.com/sysgears/apollo-fullstack-starter-kit/commit/e3cf4130bcb2bb3375ac5672e03f76677e31eadf

**Closed** 2017-01-12 15:47 UTC
Labels: wontfix

**Comment by GiladShoham** [comment] 2017-01-15 14:09
Great, will check it soon:)
